name: keuanganku
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.0
  fl_chart: ^0.68.0
  image_picker: ^0.8.7+5
  google_mlkit_text_recognition: ^0.13.0
  path_provider: ^2.0.14
  flutter_nfc_kit: ^3.3.0
  lottie: ^3.1.2
  

 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
